/// @DnDAction : YoYo Games.Audio.Stop_Audio
/// @DnDVersion : 1
/// @DnDHash : 2CBC6956
/// @DnDApplyTo : {SM64LANDFILESELECTOVERLAYMODEL}
/// @DnDArgument : "soundid" "SM64HACKSM64LADFILESELECTBYKAZEEMANUAR"
/// @DnDSaveInfo : "soundid" "SM64HACKSM64LADFILESELECTBYKAZEEMANUAR"
with(SM64LANDFILESELECTOVERLAYMODEL) audio_stop_sound(SM64HACKSM64LADFILESELECTBYKAZEEMANUAR);