script_execute(bombheired000000000message);
show_message("hey the new hereos with the mustach here");
show_message("are you found the main hereos for this world ?");
show_message("he wear a red cap and he has a mustach just like you");
show_message("no? ah yes after the hereos exit this level A lot of changes");
show_message("have taken place since our DS version: first the Bob-omb king is back");
show_message("at the top of the mountain and he wants his revenge");
show_message("As a result, towers are back all over the level");
show_message("The Bob-Omb King make an area for wait fight with you in");
show_message("this level and now we have a pond also in this level");
show_message("and tons of shines sprites appear on the map find all thanks");