script_execute(redguardskmessage);
show_message("Hello Welcome to Spaghetti Kingdom");
show_message("Bonjour Bienvenue au Royaume Spaghetti");
show_message("The Pincess Fala Wait You GalaxyHackerNewer");
show_message("La Princesse Fala T'attends GalaxyPirateInform");
show_message("atiquePlusRecent");
show_message("You speak to me after press T button but i'm not");
show_message("Only PNJ to speak it others appears in various KINGDOMS");
show_message("Tu me parle après avoir cliqué T bouton mais je ne suis pas");
show_message("Seul PNJ qui parle d'autres apparaît dans les différents ROYAUMES");
