script_execute(nokonokospeedermessage);
show_message("Hey hello i'm Koopa The Quick are you found Mario i search in a long time but i not found");
show_message("i meet before in 1996 and more recently in 2004-2005");
show_message("you possibility to replace for a small time for my short race thanks");
show_message("because you are a new hero to save new BOB-OMB battlefied now");
show_message("so deal ?  wait tell ready and you can start");
show_message("ready?");
show_message("press R to start race or click on S to skip");
show_message("R=start race");
show_message("S=skip race");